### ISSUE TITLE
Domoticz doenst start after update

### ISSUE THREAD

**Issue by niekniek89** [linuxserver/docker-domoticz#101]
Hello,

I am currently using domoticz in Docker.
Use these:

lscr.io/linuxserver/domoticz

after I update domoticz, I get the following error:

2022-01-31 12:22:26.980 Error: Please specify a web root path

I used the following to roll out the contrainer:
docker run -d \
   --name=domoticz \
   -e PUID=1000 \
   -e PGID=1000 \
   -e TZ=Europe/Amsterdam \
   -p 8080:8080 \
   -p 6144:6144 \
   -p 1443:1443 \
   -v /home/docker/domoticz:/config \
   --restart unless-stopped \
   lscr.io/linuxserver/domoticz

I've deleted both the container and the image but after recreating it still doesn't work.
still the same error.
could you maybe help me?

**Comment by ilexpl01** [comment]
Have the same issue.

**Comment by Frank071** [comment]
I think I have the same issue. The log shows repetitive
![afbeelding](https://user-images.githubusercontent.com/807403/151873026-b2170473-5e37-4327-96fb-7936036801ab.png)
Starting afresh (with an empty config) does not solve it

**Comment by L-Oosterloo** [comment]
I have the same issue. 
However if I add the optional environment variable WEBROOT=domoticz then I can get the UI via http://IP:8080/domoticz/

Not sure why the environment variable does no longer seem to be optional in this image

**Comment by niekniek89** [comment]
> I have the same issue. However if I add the optional environment variable WEBROOT=domoticz then I can get the UI via http://IP:8080/domoticz/
> 
> Not sure why the environment variable does no longer seem to be optional in this image

This works for me now, thnx.

**Comment by tobbenb** [comment]
Domoticz have probably changed something in their new release, until we have fixed the issue, please use a previous tag.

**Comment by csutcliff** [comment]
> WEBROOT: "/"

works for me to keep the old behaviour.

edit: I'm using ansible so the syntax is probably different but just set it to "/".

**Comment by guythnick** [comment]
Having the same error, but setting this WEBROOT variable doesn't seem to fix the issue.  After adding, getting a 400 Bad Request when trying to navigate to the URL.  Running on Unraid 6.9.2.  The logs show these error:

```
2022-02-01 17:10:04.282 Status: WebServer(HTTP) startup failed on address :: with port: 8080: resolve: Host not found (authoritative), trying ::
2022-02-01 17:10:04.282 Status: WebServer(HTTP) startup failed on address :: with port: 8080: resolve: Host not found (authoritative), trying 0.0.0.0
2022-02-01 17:10:04.282 Status: WebServer(HTTP) started on address: 0.0.0.0 with port 8080
2022-02-01 17:10:04.284 Status: WebServer(SSL) startup failed on address :: with port: 1443: resolve: Host not found (authoritative), trying ::
2022-02-01 17:10:04.286 Status: WebServer(SSL) startup failed on address :: with port: 1443: resolve: Host not found (authoritative), trying 0.0.0.0
```

**Comment by niekniek89** [comment]
> > WEBROOT: "/"
> 
> works for me to keep the old behaviour.
> 
> edit: I'm using ansible so the syntax is probably different but just set it to "/".

this is a great solution for me.

**Comment by L-Oosterloo** [comment]
WEBROOT=/ does not solve the problem. Some json calls on custom sensors no longer work and return a 404. with WEBROOT = domoticz these calls work fine

2022-02-06 00:14:00.303 Error: Error opening url: http://0.0.0.0:8080///json.htm?range=month&sensor=counter&type=graph&actmonth=2&idx=26
2022-02-06 00:14:00.467 Error: dzVents: Error: (3.1.8) AnnualEnergyCost: HTTP/1.1 response: 404 ==>> Not Found
2022-02-06 00:14:00.479 Error: dzVents: Error: (3.1.8) AnnualEnergyCost: An error occurred when calling event handler init with current period settings
2022-02-06 00:14:00.479 Error: dzVents: Error: (3.1.8) AnnualEnergyCost: .../generated_scripts/init with current period settings.lua:197: attempt to index a nil value (field 'json')

**Comment by tobbenb** [comment]
@L-Oosterloo 
Does it work if you comment out the -webroot line in /etc/services.d/domoticz/run?

**Comment by L-Oosterloo** [comment]
@tobbenb 
Unfortunately that does not work. Still the same errors,

**Comment by tobbenb** [comment]
Then it's not related to this issue and either has to do with your setup or a bug in domoticz.
